#!/bin/sh
yum -y install httpd php mysql php-mysql

case $(ps -p 1 -o comm | tail -1) in
systemd) systemctl enable --now httpd ;;
init) chkconfig httpd on; service httpd start ;;
*) echo "Error starting httpd (OS not using init or systemd)." 2>&1
esac

if [ ! -f /var/www/html/ec2-linux-web.tar.gz ]; then
cd /var/www/html
wget https://github.com/mzcsainthm/AWS_HOL_101/blob/main/ec2-linux-web.tar.gz
tar -zxvf ec2-linux-web.tar.gz
fi
yum -y update
